### ISSUE TITLE
Which iTerm2 theme of this screenshot 

### ISSUE THREAD

**Issue by kingzez** [amreshpro/zsh-theme#2]
![](https://camo.githubusercontent.com/2447e10ffba8d158f1f066733d9a852f9fddb468108fd824c2007231aed0d6fb/68747470733a2f2f692e696d6775722e636f6d2f6154364f6436532e706e67
)
This iTerm2 theme looks great!, please tell me theme name

**Comment by amreshpro** [comment]
Bro theme name is amresh.zsh-theme
Installation steps in https://github.com/amreshpro/zsh-theme

**Comment by kingzez** [comment]
Thanks, I know the zsh theme color is  `amresh.zsh-theme`,  after installation the path name is not pink, so it should be iTerm2 theme + zsh theme(amresh) right ? I want to know iTerm2 theme part.

**Comment by amreshpro** [comment]
Closing
